version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    build: build/web
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ../:/srv